/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph9;
import java.awt.Color;
/**
 *
 * @author apcev
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelGreet = new javax.swing.JLabel();
        jLabelSeparate = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelSidebar = new javax.swing.JPanel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonProfile = new javax.swing.JButton();
        jButtonWallet = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonSupport = new javax.swing.JButton();
        jTabbedMain = new javax.swing.JTabbedPane();
        jPanelDashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelProfile = new javax.swing.JPanel();
        jLabelFullname = new javax.swing.JLabel();
        jLabelEmpnum = new javax.swing.JLabel();
        jLabelBirthday = new javax.swing.JLabel();
        jLabelBirthday1 = new javax.swing.JLabel();
        jLabelBirthday2 = new javax.swing.JLabel();
        jLabelBirthday3 = new javax.swing.JLabel();
        jLabelBirthday4 = new javax.swing.JLabel();
        jPanelWallet = new javax.swing.JPanel();
        jLabelPayrollTitle = new javax.swing.JLabel();
        jLabelHourlyrate = new javax.swing.JLabel();
        jLabelBasicsalary = new javax.swing.JLabel();
        jLabelRice = new javax.swing.JLabel();
        jLabelPhoneallowance = new javax.swing.JLabel();
        jLabelClothingallowance = new javax.swing.JLabel();
        jLabelSSS = new javax.swing.JLabel();
        jLabelTin = new javax.swing.JLabel();
        jLabelPagibig = new javax.swing.JLabel();
        jLabelPhilhealth = new javax.swing.JLabel();
        jLabelGrosssalary = new javax.swing.JLabel();
        jLabelWitholding = new javax.swing.JLabel();
        jLabelNetsalary = new javax.swing.JLabel();
        jPanelSupport = new javax.swing.JPanel();
        jLabelSupportHR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelSupportHR2 = new javax.swing.JLabel();
        jLabelSupportHR3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelBottom = new javax.swing.JPanel();
        jButtonLeavereq = new javax.swing.JButton();
        jButtonTimeout = new javax.swing.JButton();
        jButtonTimein = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelGreet.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabelGreet.setText("Welcome!");

        jLabelSeparate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motorph9/horizontal (2).png"))); // NOI18N
        jLabelSeparate.setText("jLabel8");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motorph9/dashboard small.png"))); // NOI18N
        jLabelLogo.setText("jLabel1");

        jLabelTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabelTitle.setText("MotorPH");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(0, 198, Short.MAX_VALUE)
                        .addComponent(jLabelSeparate, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGreet)))
                .addGap(29, 29, 29))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSeparate, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle))
                .addContainerGap())
        );

        jPanel1.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 90));

        jPanelSidebar.setBackground(new java.awt.Color(255, 255, 255));

        jButtonDashboard.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDashboardMousePressed(evt);
            }
        });
        jButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDashboardActionPerformed(evt);
            }
        });

        jButtonProfile.setBackground(new java.awt.Color(204, 204, 204));
        jButtonProfile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonProfile.setText("Profile");
        jButtonProfile.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfileActionPerformed(evt);
            }
        });

        jButtonWallet.setBackground(new java.awt.Color(204, 204, 204));
        jButtonWallet.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonWallet.setText("Wallet");
        jButtonWallet.setMaximumSize(new java.awt.Dimension(90, 23));
        jButtonWallet.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWalletActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonLogout.setText("Logout");

        jButtonSupport.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSupport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonSupport.setText("Support");
        jButtonSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSidebarLayout = new javax.swing.GroupLayout(jPanelSidebar);
        jPanelSidebar.setLayout(jPanelSidebarLayout);
        jPanelSidebarLayout.setHorizontalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelSidebarLayout.setVerticalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 320));

        jPanelDashboard.setBackground(new java.awt.Color(231, 231, 231));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motorph9/dashboard big.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Last Name, First Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Employee Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Birthday");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time-In", "Time-Out", "Total Hours"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setText("May 29, 2024");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Wednesday");

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDashboardLayout.createSequentialGroup()
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 282, Short.MAX_VALUE))
                            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))))
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(15, 15, 15))
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedMain.addTab("tab2", jPanelDashboard);

        jLabelFullname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabelFullname.setText("Last Name, First Name");

        jLabelEmpnum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmpnum.setText("Employee Number");

        jLabelBirthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthday.setText("Birthday");

        jLabelBirthday1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthday1.setText("Address");

        jLabelBirthday2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthday2.setText("Contact No.");

        jLabelBirthday3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthday3.setText("Position");

        jLabelBirthday4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthday4.setText("Supervisor");

        javax.swing.GroupLayout jPanelProfileLayout = new javax.swing.GroupLayout(jPanelProfile);
        jPanelProfile.setLayout(jPanelProfileLayout);
        jPanelProfileLayout.setHorizontalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBirthday)
                    .addComponent(jLabelEmpnum)
                    .addComponent(jLabelFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthday1)
                    .addComponent(jLabelBirthday2)
                    .addComponent(jLabelBirthday3)
                    .addComponent(jLabelBirthday4))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        jPanelProfileLayout.setVerticalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabelFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBirthday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBirthday1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBirthday2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBirthday3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBirthday4)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedMain.addTab("tab1", jPanelProfile);

        jLabelPayrollTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabelPayrollTitle.setText("Payroll Information");

        jLabelHourlyrate.setText("Hourly Rate");

        jLabelBasicsalary.setText("Basic Salary");

        jLabelRice.setText("Rice Subsidy");

        jLabelPhoneallowance.setText("Phone Allowance");

        jLabelClothingallowance.setText("Clothing Allowance");

        jLabelSSS.setText("SSS");

        jLabelTin.setText("TIN");

        jLabelPagibig.setText("Pagibig");

        jLabelPhilhealth.setText("Philhealth");

        jLabelGrosssalary.setText("Gross Salary");

        jLabelWitholding.setText("Withholding Tax");

        jLabelNetsalary.setText("Net Salary");

        javax.swing.GroupLayout jPanelWalletLayout = new javax.swing.GroupLayout(jPanelWallet);
        jPanelWallet.setLayout(jPanelWalletLayout);
        jPanelWalletLayout.setHorizontalGroup(
            jPanelWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWalletLayout.createSequentialGroup()
                .addGroup(jPanelWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelPayrollTitle))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelHourlyrate))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelBasicsalary))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelRice))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelPhoneallowance))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelClothingallowance))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelSSS))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelTin))
                    .addGroup(jPanelWalletLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelWalletLayout.createSequentialGroup()
                                .addComponent(jLabelPhilhealth)
                                .addGap(243, 243, 243)
                                .addComponent(jLabelNetsalary))
                            .addGroup(jPanelWalletLayout.createSequentialGroup()
                                .addComponent(jLabelPagibig)
                                .addGap(256, 256, 256)
                                .addComponent(jLabelGrosssalary))
                            .addComponent(jLabelWitholding))))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanelWalletLayout.setVerticalGroup(
            jPanelWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWalletLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabelPayrollTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabelHourlyrate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBasicsalary)
                .addGap(18, 18, 18)
                .addComponent(jLabelRice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPhoneallowance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClothingallowance)
                .addGap(18, 18, 18)
                .addComponent(jLabelSSS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPagibig)
                    .addComponent(jLabelGrosssalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNetsalary)
                    .addComponent(jLabelPhilhealth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWitholding)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedMain.addTab("tab3", jPanelWallet);

        jLabelSupportHR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSupportHR.setText("HR Department");

        jLabel1.setText("hr@motorph.com");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Support");

        jLabelSupportHR2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSupportHR2.setText("Accounting Department");

        jLabelSupportHR3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSupportHR3.setText("IT Department");

        jLabel6.setText("it@motorph.com");

        jLabel7.setText("accounting@motorph.com");

        javax.swing.GroupLayout jPanelSupportLayout = new javax.swing.GroupLayout(jPanelSupport);
        jPanelSupport.setLayout(jPanelSupportLayout);
        jPanelSupportLayout.setHorizontalGroup(
            jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupportLayout.createSequentialGroup()
                .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSupportLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8))
                    .addGroup(jPanelSupportLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSupportHR)
                            .addComponent(jLabelSupportHR3)
                            .addComponent(jLabelSupportHR2))
                        .addGap(73, 73, 73)
                        .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanelSupportLayout.setVerticalGroup(
            jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupportLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel8)
                .addGap(46, 46, 46)
                .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupportHR)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupportHR2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupportHR3)
                    .addComponent(jLabel6))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedMain.addTab("tab4", jPanelSupport);

        jPanel1.add(jTabbedMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, -42, -1, 450));

        jPanelBottom.setBackground(new java.awt.Color(255, 255, 255));

        jButtonLeavereq.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLeavereq.setText("Leave Request");
        jButtonLeavereq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeavereqActionPerformed(evt);
            }
        });

        jButtonTimeout.setBackground(new java.awt.Color(204, 204, 204));
        jButtonTimeout.setText("Time-Out");

        jButtonTimein.setBackground(new java.awt.Color(0, 255, 0));
        jButtonTimein.setText("Time-In");

        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonLeavereq)
                .addGap(33, 33, 33)
                .addComponent(jButtonTimeout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jButtonTimein)
                .addGap(25, 25, 25))
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLeavereq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimein, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 580, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLeavereqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeavereqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeavereqActionPerformed

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        // TODO add your handling code here:
        jTabbedMain.setSelectedIndex(0);
        jButtonDashboard.setBackground(Color.PINK);
        jButtonProfile.setBackground(Color.LIGHT_GRAY);
        jButtonWallet.setBackground(Color.LIGHT_GRAY);
        jButtonSupport.setBackground(Color.LIGHT_GRAY);
        
        
                
        
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfileActionPerformed
        // TODO add your handling code here:
        jTabbedMain.setSelectedIndex(1);
        jButtonDashboard.setBackground(Color.LIGHT_GRAY);
        jButtonProfile.setBackground(Color.PINK);
        jButtonWallet.setBackground(Color.LIGHT_GRAY);
        jButtonSupport.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonProfileActionPerformed

    private void jButtonWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWalletActionPerformed
        // TODO add your handling code here:
        jTabbedMain.setSelectedIndex(2);
        jButtonDashboard.setBackground(Color.LIGHT_GRAY);
        jButtonProfile.setBackground(Color.LIGHT_GRAY);
        jButtonWallet.setBackground(Color.PINK);
        jButtonSupport.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonWalletActionPerformed

    private void jButtonDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDashboardMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDashboardMousePressed

    private void jButtonSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupportActionPerformed
        // TODO add your handling code here:
        jTabbedMain.setSelectedIndex(3);
        jButtonDashboard.setBackground(Color.LIGHT_GRAY);
        jButtonProfile.setBackground(Color.LIGHT_GRAY);
        jButtonWallet.setBackground(Color.LIGHT_GRAY);
        jButtonSupport.setBackground(Color.PINK);
    }//GEN-LAST:event_jButtonSupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonLeavereq;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonProfile;
    private javax.swing.JButton jButtonSupport;
    private javax.swing.JButton jButtonTimein;
    private javax.swing.JButton jButtonTimeout;
    private javax.swing.JButton jButtonWallet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBasicsalary;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JLabel jLabelBirthday1;
    private javax.swing.JLabel jLabelBirthday2;
    private javax.swing.JLabel jLabelBirthday3;
    private javax.swing.JLabel jLabelBirthday4;
    private javax.swing.JLabel jLabelClothingallowance;
    private javax.swing.JLabel jLabelEmpnum;
    private javax.swing.JLabel jLabelFullname;
    private javax.swing.JLabel jLabelGreet;
    private javax.swing.JLabel jLabelGrosssalary;
    private javax.swing.JLabel jLabelHourlyrate;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNetsalary;
    private javax.swing.JLabel jLabelPagibig;
    private javax.swing.JLabel jLabelPayrollTitle;
    private javax.swing.JLabel jLabelPhilhealth;
    private javax.swing.JLabel jLabelPhoneallowance;
    private javax.swing.JLabel jLabelRice;
    private javax.swing.JLabel jLabelSSS;
    private javax.swing.JLabel jLabelSeparate;
    private javax.swing.JLabel jLabelSupportHR;
    private javax.swing.JLabel jLabelSupportHR2;
    private javax.swing.JLabel jLabelSupportHR3;
    private javax.swing.JLabel jLabelTin;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelWitholding;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JPanel jPanelSupport;
    private javax.swing.JPanel jPanelWallet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedMain;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
