
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class LogIn extends javax.swing.JFrame {
    
    private empDashboard empDash;

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jPass = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logopic/motorlogonew.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picUser/padlockk.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picUser/usernamme.png"))); // NOI18N

        jUser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });

        bLogin.setBackground(new java.awt.Color(204, 204, 204));
        bLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLogin.setText("Log In");
        bLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(bLogin)
                .addGap(157, 157, 157))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUser)
                            .addComponent(jPass, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(45, 45, 45)
                .addComponent(bLogin)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jUserActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed


        if (jUser.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Fill Out Username!");
        }
     
        else if (jPass.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Fill Out Password!");
        }
        
         else if (jUser.getText().contains("garciaManuel") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         // open employeeDetails
         empDashboard empDashboard = empDash= new empDashboard();
         empDash.show();
         dispose();
            
     
         }
         else if (jUser.getText().contains("antonioLim") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         }
         else if (jUser.getText().contains("aquinoBianca") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("reyesIsabella") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("hernandezEduard") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("villanuevaAndrea") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("sanjoseBrad") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("romualdezAlice") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("atienzaRosie") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("alvaroRoderick") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("salcedoAnthony") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("lopezJosie") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("faralaMartha") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("martinezLeila") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("romualdezFredrick") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         }
         else if (jUser.getText().contains("mataChristian") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("deleonSelena") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("sanjoseAllison") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("rosarioCydney") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("bautistaMark") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("lazaroDarlene") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("delossantosKolby") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("santosVella") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("delrosarioTomas") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("tolentinoJacklyn") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("gutierrezPercival") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("manalaysayGarfield") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("villegasLizeth") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("ramosCarol") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("macedaEmilia") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("aguilarDelia") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("castroJohnraf") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("martinezCarlos") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
         else if (jUser.getText().contains("santosBeatriz") && jPass.getText().contains("123")){
         JOptionPane.showMessageDialog(null, "Login Successful");
         } 
 
        else {
         JOptionPane.showMessageDialog(null, "Wrong Username or Password!", "Message", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_bLoginActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()){
            jPass.setEchoChar((char)0);
        }
        else {
            jPass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JTextField jUser;
    // End of variables declaration//GEN-END:variables
}
